### ISSUE TITLE
Class Civi\\Api4\\Contact not found

### ISSUE THREAD

**Issue by kainhofer** [awasson/civiCPD#2]
I'm trying this extension with the latest CiviCRM-Version and whenever I go to a member page in the WordPress CiviCRM backend, a PHP error is thrown:

```
[Mon Apr 22 13:03:32.037658 2019] [proxy_fcgi:error] [pid 3491:tid 140010397316864] [client 212.183.126.148:40724] AH01071: Got error 'PHP message: 
PHP Fatal error:  Uncaught Error: Class 'Civi\\Api4\\Contact' not found in /var/www/vhosts/avoe.at/staging.avoe.at/wp-content/uploads/civicrm/ext/org.civicrm.contactlayout/CRM/Contactlayout/BAO/ContactLayout.php:18
Stack trace:
#0 /var/www/vhosts/avoe.at/staging.avoe.at/wp-content/uploads/civicrm/ext/org.civicrm.contactlayout/contactlayout.php(133): CRM_Contactlayout_BAO_ContactLayout::getLayout('203')
#1 /var/www/vhosts/avoe.at/staging.avoe.at/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(270): contactlayout_civicrm_pageRun(Object(CRM_Contact_Page_View_Summary))
#2 /var/www/vhosts/avoe.at/staging.avoe.at/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(155): CRM_Utils_Hook->runHooks(Array, 'civicrm_pageRun', 1, Object(CRM_Contact_Page_View_Summary), NULL, NULL, NULL, NULL, NULL)
#3 /var/www/vhosts/avoe.at/staging.avoe.at/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(86): CRM_Utils_Hook_WordPress->invokeViaUF(1, Object(CRM_Contact_Page_View_Summary)...

referer: https://staging.avoe.at/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fcontact%2Fsearch&_qf_Basic_display=true&qfKey=ff7e3089b8a314f30b65541cdc09d462_1689
```

**Comment by kainhofer** [comment]
Nevermind, this was an issue with a different extension I installed shortly before (and didn't realize wasn't working...)
